# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19d89ab9ef8641cd758ab6364762c19df869a0909597f7d8d848b7ae8d33c28f0490712908a6cd610b925091d540ace42305359fe1c9b2f17696b67a047e4ce5

test:
  secret_key_base: 601fd5555aad3465a7ba4690334b0204cc5ec7a68859e74cccb415a8657e36abedaccdc3198df56aa5ccd6d1fe1cede53dc3532b990d95a42d09af63aab96cd0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
